name: Shard

on:
  push:
    paths:
      - 'shard/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Gradle
        run: |
          chmod +x ./gradlew
          ./gradlew :shard:clean build
      - name: Build Image
        env:
          IMAGE: votebot/shard
          DOCKER_USER: ${{ secrets.SPACE_USERNAME }}
          DOCKER_PASSWD: ${{ secrets.SPACE_PASSWORD }}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWD
          docker build -t ${IMAGE} . -f Dockerfile
          docker tag ${IMAGE} ${IMAGE}:latest
          docker tag ${IMAGE} ${IMAGE}:${GITHUB_SHA::8}
          docker push ${IMAGE}